spring.application.name=game

spring.data.mongodb.uri=mongodb+srv://root:adAD112%40%28%29@sudoku.afpliut.mongodb.net/sudoku
spring.data.mongodb.auto-index-creation=true

# spring.security.oauth2.client.registration.github.client-id=Ov23liwy1N9qag3Yk1KT
# spring.security.oauth2.client.registration.github.client-secret=7a7c59f45aedeb93a8a0ad94edf91c4792651532