spring.application.name=game

spring.security.user.name=root
spring.security.user.password=1234

spring.data.mongodb.uri=mongodb+srv://root:<db_password>@sudoku.afpliut.mongodb.net/?appName=Sudoku
spring.data.mongodb.auto-index-creation=true